#include <Arduino.h>
#include <HX711.h>
#include <Adafruit_NeoPixel.h>
#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEUtils.h>
#include <BLE2902.h>
#include <Preferences.h>
#include "dyno_protocol.h"

// Verify every pin, PWM frequency, valve polarity, and mechanical limit on an
// unloaded bench before connecting an engine. Raw duty zero is the only
// disarmed/fault/E-stop output state in protocol v5.
static const uint8_t LED_PIN=48,ESTOP_PIN=1,RESET_PIN=42,HX_DOUT=4,HX_CLK=5,ENGINE_RPM_PIN=6,PUMP_RPM_PIN=9,THROTTLE_PIN=7,FLOW_PIN=10,FLOW_ENABLE=11,PRESSURE_PIN=12,PRESSURE_ENABLE=13;
static const uint8_t FLOW_CH=1,PRESSURE_CH=2,THROTTLE_CH=3,PWM_BITS=12;
static const uint16_t PWM_RAW_MAX=(1U<<PWM_BITS)-1U;
static const uint32_t WATCHDOG_MS=500,RPM_TIMEOUT_US=500000,CONTROL_US=20000,TELEMETRY_MS=50,RESET_DEBOUNCE_MS=100;
static const float TORQUE_HARD_NM=90.0f,RESET_RPM=50.0f,RESET_TORQUE=2.0f;
static const uint32_t NVS_MAGIC=0x44594D35UL; static const uint16_t NVS_VERSION=5;

struct PidBank{float p,i,d,slew;uint8_t enabled;uint8_t reserved[3];};
struct MachineConfig{float flowMin,flowMax,pressureMin,pressureMax,pumpPpr,pumpMaxRpm,loadScale,filterAlpha;uint8_t pumpLimitEnabled;uint8_t reserved[3];PidBank pid[6];};
struct PersistentMachine{uint32_t magic;uint16_t version;uint16_t reserved;MachineConfig machine;uint32_t crc32;};
struct ActiveSetup{bool valid,cvt,engineSensor,engineLimit;float engineToPump,cvtOutputToPump,enginePpr,closedUs,fullUs,servoHz,engineMax,stallRpm,recoveryRpm,recoveryTimeout;};
struct PidState{float integral,previous,output;bool initialized;};

HX711 scale; Adafruit_NeoPixel led(1,LED_PIN,NEO_GRB+NEO_KHZ800); Preferences prefs;
BLEServer*server=nullptr;BLECharacteristic*cmdChar=nullptr;BLECharacteristic*telChar=nullptr;BLECharacteristic*configChar=nullptr;
portMUX_TYPE cmdMux=portMUX_INITIALIZER_UNLOCKED,configMux=portMUX_INITIALIZER_UNLOCKED,pulseMux=portMUX_INITIALIZER_UNLOCKED;
CommandPacket pendingCommand{};ConfigPacket pendingConfig{};volatile bool commandPending=false,configPending=false,bleConnected=false,disconnectPending=false;
volatile uint32_t engineNewest=0,enginePrevious=0,engineCount=0,pumpNewest=0,pumpPrevious=0,pumpCount=0;
MachineConfig machine{};ActiveSetup setupConfig{};PidState pidState[6]{};CommandPacket command{};DynoSystemState state=STATE_BOOT;uint32_t faults=FAULT_NONE,lastCommandMs=0,lastCommandSequence=0,lastControlUs=0,lastTelemetryMs=0;
float engineSensorRpm=0,selectedEngineRpm=0,pumpRpm=0,torqueNm=0,filteredTorque=0,flowRawPct=0,pressureRawPct=0,throttlePct=0;bool engineValid=false,pumpValid=false,torqueValid=false,scaleConnected=false,antiStall=false;uint32_t stallStartedMs=0;

void setDefaults(){machine={0,98,0,98,4,3000,2280,.2f,1,{0,0,0},{}};for(int i=0;i<6;i++){machine.pid[i]={.1f,.02f,.005f,100,0,{0,0,0}};}machine.pid[0]={1,.2f,.05f,100,0,{0,0,0}};}
bool machineValid(const MachineConfig&m){if(!(m.flowMin>=0&&m.flowMin<m.flowMax&&m.flowMax<=99&&m.pressureMin>=0&&m.pressureMin<m.pressureMax&&m.pressureMax<=99))return false;if(!isfinite(m.pumpPpr)||m.pumpPpr<=0||!isfinite(m.pumpMaxRpm)||m.pumpMaxRpm<=0||!isfinite(m.loadScale)||fabsf(m.loadScale)<1||!isfinite(m.filterAlpha)||m.filterAlpha<.001f||m.filterAlpha>1)return false;for(int i=0;i<6;i++)if(!isfinite(m.pid[i].p)||m.pid[i].p<0||!isfinite(m.pid[i].i)||m.pid[i].i<0||!isfinite(m.pid[i].d)||m.pid[i].d<0||!isfinite(m.pid[i].slew)||m.pid[i].slew<=0)return false;return true;}
bool saveMachine(){PersistentMachine p{};p.magic=NVS_MAGIC;p.version=NVS_VERSION;p.machine=machine;p.crc32=dynoCrc32((uint8_t*)&p,offsetof(PersistentMachine,crc32));if(!prefs.begin("dyno-v5",false))return false;size_t n=prefs.putBytes("machine",&p,sizeof(p));prefs.end();return n==sizeof(p);}
bool loadMachine(){if(!prefs.begin("dyno-v5",true))return false;PersistentMachine p{};size_t n=prefs.getBytesLength("machine")==sizeof(p)?prefs.getBytes("machine",&p,sizeof(p)):0;prefs.end();if(n!=sizeof(p)||p.magic!=NVS_MAGIC||p.version!=NVS_VERSION||p.crc32!=dynoCrc32((uint8_t*)&p,offsetof(PersistentMachine,crc32))||!machineValid(p.machine))return false;machine=p.machine;return true;}
void clearPid(){for(auto&s:pidState)s={0,0,0,false};}
float clampf(float v,float lo,float hi){return v<lo?lo:v>hi?hi:v;}
float normalizedToFlowRaw(float u){return machine.flowMin+(machine.flowMax-machine.flowMin)*clampf(u,0,100)/100;}
float normalizedToPressureRaw(float u){return machine.pressureMax-(machine.pressureMax-machine.pressureMin)*clampf(u,0,100)/100;}
uint32_t rawDuty(float pct){return (uint32_t)(clampf(pct,0,99)*PWM_RAW_MAX/100);}
uint32_t servoDuty(float percent){float pulse=setupConfig.closedUs+(setupConfig.fullUs-setupConfig.closedUs)*clampf(percent,0,100)/100;float period=1000000.0f/setupConfig.servoHz;return (uint32_t)clampf(pulse*PWM_RAW_MAX/period,0,PWM_RAW_MAX);}
void failSafe(){digitalWrite(FLOW_ENABLE,LOW);digitalWrite(PRESSURE_ENABLE,LOW);ledcWrite(FLOW_CH,0);ledcWrite(PRESSURE_CH,0);ledcWrite(THROTTLE_CH,0);flowRawPct=pressureRawPct=throttlePct=0;}
void writeOutputs(){if(state!=STATE_ARMED){failSafe();return;}bool manual=command.mode==MODE_MANUAL;bool pressure=command.controlFlags&CMD_PRESSURE_ACTUATOR;digitalWrite(FLOW_ENABLE,(manual||!pressure)?HIGH:LOW);digitalWrite(PRESSURE_ENABLE,(manual||pressure)?HIGH:LOW);ledcWrite(FLOW_CH,(manual||!pressure)?rawDuty(flowRawPct):0);ledcWrite(PRESSURE_CH,(manual||pressure)?rawDuty(pressureRawPct):0);ledcWrite(THROTTLE_CH,servoDuty(throttlePct));}
void enterState(DynoSystemState next,uint32_t fault=0){if(fault)faults|=fault;state=next;clearPid();antiStall=false;stallStartedMs=0;if(next!=STATE_ARMED)failSafe();}

void IRAM_ATTR engineIsr(){uint32_t now=micros();portENTER_CRITICAL_ISR(&pulseMux);enginePrevious=engineNewest;engineNewest=now;engineCount++;portEXIT_CRITICAL_ISR(&pulseMux);}
void IRAM_ATTR pumpIsr(){uint32_t now=micros();portENTER_CRITICAL_ISR(&pulseMux);pumpPrevious=pumpNewest;pumpNewest=now;pumpCount++;portEXIT_CRITICAL_ISR(&pulseMux);}
float pulseRpm(volatile uint32_t&newest,volatile uint32_t&previous,volatile uint32_t&count,float ppr,bool&valid){uint32_t n,p,c;portENTER_CRITICAL(&pulseMux);n=newest;p=previous;c=count;portEXIT_CRITICAL(&pulseMux);uint32_t interval=n-p;if(c<2||!n||!interval||(uint32_t)(micros()-n)>RPM_TIMEOUT_US){valid=false;return 0;}float rpm=60000000.0f/(interval*ppr);valid=isfinite(rpm)&&rpm>=0&&rpm<100000;return valid?rpm:0;}
void readSensors(){engineSensorRpm=pulseRpm(engineNewest,enginePrevious,engineCount,setupConfig.enginePpr>0?setupConfig.enginePpr:1,engineValid);pumpRpm=pulseRpm(pumpNewest,pumpPrevious,pumpCount,machine.pumpPpr,pumpValid);selectedEngineRpm=setupConfig.cvt||setupConfig.engineSensor?engineSensorRpm:(pumpValid?pumpRpm/setupConfig.engineToPump:0);if(scaleConnected&&scale.is_ready()){float sample=scale.get_units(1);if(isfinite(sample)){filteredTorque=torqueValid?machine.filterAlpha*sample+(1-machine.filterAlpha)*filteredTorque:sample;torqueNm=filteredTorque;torqueValid=true;}else torqueValid=false;}else torqueValid=false;}

bool activeFaultGone(){if(digitalRead(ESTOP_PIN)==LOW)return false;if(machine.pumpLimitEnabled&&pumpRpm>=machine.pumpMaxRpm)return false;if(setupConfig.engineLimit&&selectedEngineRpm>=setupConfig.engineMax)return false;if(fabsf(torqueNm)>=TORQUE_HARD_NM)return false;return true;}
bool resetSafe(){return activeFaultGone()&&flowRawPct==0&&pressureRawPct==0&&throttlePct==0&&pumpRpm<RESET_RPM&&selectedEngineRpm<RESET_RPM&&fabsf(torqueNm)<RESET_TORQUE&&bleConnected;}
bool physicalResetSafe(){return activeFaultGone()&&flowRawPct==0&&pressureRawPct==0&&throttlePct==0&&pumpRpm<RESET_RPM&&selectedEngineRpm<RESET_RPM&&fabsf(torqueNm)<RESET_TORQUE;}
int requiredPid(){bool pressure=command.controlFlags&CMD_PRESSURE_ACTUATOR;if(command.mode==MODE_TORQUE)return pressure?0:3;if(command.mode==MODE_ENGINE_RPM)return pressure?1:4;if(command.mode==MODE_RPM)return pressure?2:5;return -1;}
bool commandValid(const CommandPacket&c){if(!dynoPacketValid(c)||c.mode>MODE_ENGINE_RPM||c.manualFlowPct>100||c.manualPressurePct>100||c.manualThrottlePct>100)return false;if(!isfinite(c.targetTorqueNm)||c.targetTorqueNm<0||!isfinite(c.targetPumpRpm)||c.targetPumpRpm<0||!isfinite(c.targetEngineRpm)||c.targetEngineRpm<0)return false;return true;}

void processCommand(){if(!commandPending)return;CommandPacket next{};portENTER_CRITICAL(&cmdMux);next=pendingCommand;commandPending=false;portEXIT_CRITICAL(&cmdMux);if(!commandValid(next)){if(state==STATE_ARMED)enterState(STATE_FAULT,FAULT_INVALID_COMMAND);return;}if((int32_t)(next.sequence-lastCommandSequence)<=0)return;command=next;lastCommandSequence=next.sequence;lastCommandMs=millis();if(next.emergency){enterState(STATE_ESTOP);return;}if(next.controlFlags&CMD_SATURATION_FAULT){enterState(STATE_FAULT,FAULT_TARGET_SATURATION);return;}if(next.controlFlags&CMD_CLEAR_LATCH){if(resetSafe()){faults=FAULT_NONE;enterState(STATE_DISARMED);}return;}if(!next.arm){if(state==STATE_ARMED)enterState(STATE_DISARMED);return;}if(state==STATE_DISARMED){if(!setupConfig.valid){enterState(STATE_FAULT,FAULT_SETUP_REQUIRED);return;}int bank=requiredPid();if(bank>=0&&!machine.pid[bank].enabled){enterState(STATE_FAULT,FAULT_UNSUPPORTED_MODE);return;}state=STATE_ARMED;clearPid();}}

bool configValid(const ConfigPacket&c){if(!dynoPacketValid(c)||c.kind>CONFIG_ACTIVE_SETUP)return false;for(float v:c.values)if(!isfinite(v))return false;if(c.kind==CONFIG_PID&&c.index>=6)return false;return true;}
void publishConfig(const ConfigPacket&c){ConfigPacket ack=c;dynoFinalize(ack);configChar->setValue((uint8_t*)&ack,sizeof(ack));}
void processConfig(){if(!configPending)return;ConfigPacket c{};portENTER_CRITICAL(&configMux);c=pendingConfig;configPending=false;portEXIT_CRITICAL(&configMux);if(state!=STATE_DISARMED||!configValid(c))return;if(c.actionFlags&CONFIG_RESTORE_DEFAULTS){setDefaults();saveMachine();publishConfig(c);return;}if(c.kind==CONFIG_MACHINE){MachineConfig candidate=machine;candidate.flowMin=c.values[0];candidate.flowMax=c.values[1];candidate.pressureMin=c.values[2];candidate.pressureMax=c.values[3];candidate.pumpPpr=c.values[4];candidate.pumpMaxRpm=c.values[5];candidate.loadScale=c.values[6];candidate.filterAlpha=c.values[7];candidate.pumpLimitEnabled=bool(c.actionFlags&CONFIG_PUMP_LIMIT);if(!machineValid(candidate))return;if((c.actionFlags&CONFIG_TARE)&&(pumpRpm>=RESET_RPM||selectedEngineRpm>=RESET_RPM))return;machine=candidate;scale.set_scale(machine.loadScale);if(c.actionFlags&CONFIG_TARE)scale.tare(15);}
  else if(c.kind==CONFIG_PID){PidBank b{c.values[0],c.values[1],c.values[2],c.values[3],(uint8_t)bool(c.actionFlags&CONFIG_ENABLED),{0,0,0}};if(b.p<0||b.i<0||b.d<0||b.slew<=0)return;machine.pid[c.index]=b;}
  else{ActiveSetup s{};s.cvt=c.actionFlags&CONFIG_SETUP_CVT;s.engineSensor=c.actionFlags&CONFIG_ENGINE_SENSOR;s.engineLimit=c.actionFlags&CONFIG_ENGINE_LIMIT;s.engineToPump=c.values[0];s.cvtOutputToPump=c.values[1];s.enginePpr=c.values[2];s.closedUs=c.values[3];s.fullUs=c.values[4];s.servoHz=c.values[5];s.engineMax=c.values[6];s.stallRpm=c.values[7];s.recoveryRpm=c.values[8];s.recoveryTimeout=c.values[9];s.valid=s.engineToPump>0&&s.cvtOutputToPump>0&&s.enginePpr>0&&s.closedUs>0&&s.fullUs>0&&s.closedUs!=s.fullUs&&s.servoHz>0&&s.engineMax>0&&s.stallRpm>0&&s.recoveryRpm>s.stallRpm&&s.recoveryTimeout>0;if(!s.valid)return;setupConfig=s;ledcSetup(THROTTLE_CH,(uint32_t)s.servoHz,PWM_BITS);ledcAttachPin(THROTTLE_PIN,THROTTLE_CH);}
  if((c.actionFlags&CONFIG_SAVE_NVS)&&c.kind!=CONFIG_ACTIVE_SETUP){saveMachine();}
  publishConfig(c);
}

float runPid(int index,float error,float dt){PidBank&b=machine.pid[index];PidState&s=pidState[index];if(!s.initialized){s.previous=error;s.integral=0;s.initialized=true;}s.integral=clampf(s.integral+error*dt,-10000,10000);float derivative=(error-s.previous)/dt;float desired=clampf(b.p*error+b.i*s.integral+b.d*derivative,0,100);float step=b.slew*dt;s.output=clampf(desired,s.output-step,s.output+step);s.previous=error;return s.output;}
void runControl(float dt){if(state!=STATE_ARMED)return;bool pressure=command.controlFlags&CMD_PRESSURE_ACTUATOR;flowRawPct=pressureRawPct=0;if(command.mode==MODE_MANUAL){flowRawPct=normalizedToFlowRaw(command.manualFlowPct);pressureRawPct=normalizedToPressureRaw(command.manualPressurePct);throttlePct=command.manualThrottlePct;return;}int bank=requiredPid();float error=0;if(command.mode==MODE_TORQUE)error=command.targetTorqueNm-torqueNm;else if(command.mode==MODE_ENGINE_RPM)error=pressure?selectedEngineRpm-command.targetEngineRpm:command.targetEngineRpm-selectedEngineRpm;else if(command.mode==MODE_RPM)error=pressure?pumpRpm-command.targetPumpRpm:command.targetPumpRpm-pumpRpm;else{enterState(STATE_FAULT,FAULT_UNSUPPORTED_MODE);return;}float normalized=runPid(bank,error,dt);if(pressure)pressureRawPct=normalizedToPressureRaw(normalized);else flowRawPct=normalizedToFlowRaw(normalized);throttlePct=(command.controlFlags&CMD_MANUAL_THROTTLE)?command.manualThrottlePct:0;
  // Direct-engine anti-stall never switches actuators. Flow unloads to configured
  // maximum flow; pressure unloads to normalized zero braking.
  if(!setupConfig.cvt&&throttlePct>5&&selectedEngineRpm<setupConfig.stallRpm){if(!stallStartedMs)stallStartedMs=millis();antiStall=true;pidState[bank].integral=0;if(pressure)pressureRawPct=normalizedToPressureRaw(0);else flowRawPct=normalizedToFlowRaw(100);if(millis()-stallStartedMs>(uint32_t)(setupConfig.recoveryTimeout*1000))enterState(STATE_FAULT,FAULT_ANTI_STALL_TIMEOUT);}else if(antiStall&&selectedEngineRpm<setupConfig.recoveryRpm){if(pressure)pressureRawPct=normalizedToPressureRaw(0);else flowRawPct=normalizedToFlowRaw(100);}else{antiStall=false;stallStartedMs=0;}}

void evaluateSafety(){if(digitalRead(ESTOP_PIN)==LOW){enterState(STATE_ESTOP);return;}if(state==STATE_ARMED&&millis()-lastCommandMs>WATCHDOG_MS){enterState(STATE_FAULT,FAULT_COMMAND_TIMEOUT);return;}if(state==STATE_ARMED&&disconnectPending){enterState(STATE_FAULT,FAULT_BLE_DISCONNECTED);disconnectPending=false;return;}if(state==STATE_ARMED&&machine.pumpLimitEnabled&&pumpRpm>=machine.pumpMaxRpm){enterState(STATE_FAULT,FAULT_PUMP_OVERSPEED);return;}if(state==STATE_ARMED&&setupConfig.engineLimit&&selectedEngineRpm>=setupConfig.engineMax){enterState(STATE_FAULT,FAULT_ENGINE_OVERSPEED);return;}if(state==STATE_ARMED&&fabsf(torqueNm)>=TORQUE_HARD_NM){enterState(STATE_FAULT,FAULT_TORQUE_OVERRANGE);return;}if(state==STATE_ARMED&&!pumpValid){enterState(STATE_FAULT,FAULT_PUMP_RPM_SENSOR);return;}if(state==STATE_ARMED&&(setupConfig.cvt||setupConfig.engineSensor)&&!engineValid){enterState(STATE_FAULT,FAULT_ENGINE_RPM_SENSOR);return;}if(state==STATE_ARMED&&!torqueValid){enterState(STATE_FAULT,FAULT_TORQUE_SENSOR);return;}}
void physicalReset(){static uint32_t pressed=0;if(digitalRead(RESET_PIN)==LOW){pressed=pressed?pressed:millis();if(millis()-pressed>RESET_DEBOUNCE_MS&&physicalResetSafe()){faults=FAULT_NONE;enterState(STATE_DISARMED);}}else pressed=0;}

void sendTelemetry(){TelemetryPacket t{};t.magic=DYNO_PACKET_MAGIC;t.version=DYNO_PACKET_VERSION;t.state=state;t.mode=command.mode;t.faultFlags=faults;t.lastCommandSequence=lastCommandSequence;t.engineSensorRpm=engineSensorRpm;t.selectedEngineRpm=selectedEngineRpm;t.targetEngineRpm=command.targetEngineRpm;t.pumpRpm=pumpRpm;t.targetPumpRpm=command.targetPumpRpm;t.torqueNm=torqueNm;t.targetTorqueNm=command.targetTorqueNm;t.flowValveDutyPct=flowRawPct;t.pressureValveDutyPct=pressureRawPct;t.throttlePct=throttlePct;if(state==STATE_ARMED)t.flags|=TEL_ARMED;if(state==STATE_ESTOP)t.flags|=TEL_ESTOP;if(bleConnected)t.flags|=TEL_BLE;if(scaleConnected)t.flags|=TEL_SCALE;if(engineValid)t.flags|=TEL_ENGINE_VALID;if(pumpValid)t.flags|=TEL_PUMP_VALID;if(torqueValid)t.flags|=TEL_TORQUE_VALID;if(antiStall)t.flags|=TEL_ANTI_STALL;if(setupConfig.valid)t.flags|=TEL_SETUP_VALID;if(command.controlFlags&CMD_PRESSURE_ACTUATOR)t.flags|=TEL_PRESSURE_ACTUATOR;dynoFinalize(t);telChar->setValue((uint8_t*)&t,sizeof(t));telChar->notify();}

class ServerCallbacks:public BLEServerCallbacks{void onConnect(BLEServer*)override{bleConnected=true;setupConfig.valid=false;}void onDisconnect(BLEServer*s)override{bleConnected=false;disconnectPending=true;setupConfig.valid=false;s->getAdvertising()->start();}};
class CommandCallbacks:public BLECharacteristicCallbacks{void onWrite(BLECharacteristic*c)override{std::string v=c->getValue();if(v.size()!=sizeof(CommandPacket))return;CommandPacket p{};memcpy(&p,v.data(),sizeof(p));portENTER_CRITICAL(&cmdMux);pendingCommand=p;commandPending=true;portEXIT_CRITICAL(&cmdMux);}};
class ConfigCallbacks:public BLECharacteristicCallbacks{void onWrite(BLECharacteristic*c)override{std::string v=c->getValue();if(v.size()!=sizeof(ConfigPacket))return;ConfigPacket p{};memcpy(&p,v.data(),sizeof(p));portENTER_CRITICAL(&configMux);pendingConfig=p;configPending=true;portEXIT_CRITICAL(&configMux);}};
void setupBle(){BLEDevice::init(DYNO_BLE_DEVICE_NAME);server=BLEDevice::createServer();server->setCallbacks(new ServerCallbacks());BLEService*service=server->createService(DYNO_SERVICE_UUID);cmdChar=service->createCharacteristic(DYNO_CMD_UUID,BLECharacteristic::PROPERTY_WRITE|BLECharacteristic::PROPERTY_WRITE_NR);telChar=service->createCharacteristic(DYNO_TEL_UUID,BLECharacteristic::PROPERTY_READ|BLECharacteristic::PROPERTY_NOTIFY);configChar=service->createCharacteristic(DYNO_CONFIG_UUID,BLECharacteristic::PROPERTY_READ|BLECharacteristic::PROPERTY_WRITE);cmdChar->setCallbacks(new CommandCallbacks());configChar->setCallbacks(new ConfigCallbacks());telChar->addDescriptor(new BLE2902());ConfigPacket initial{};initial.magic=DYNO_PACKET_MAGIC;initial.version=DYNO_PACKET_VERSION;initial.kind=CONFIG_MACHINE;dynoFinalize(initial);configChar->setValue((uint8_t*)&initial,sizeof(initial));service->start();BLEAdvertising*advertising=server->getAdvertising();advertising->addServiceUUID(DYNO_SERVICE_UUID);advertising->start();}

void setup(){Serial.begin(115200);pinMode(ESTOP_PIN,INPUT_PULLUP);pinMode(RESET_PIN,INPUT_PULLUP);pinMode(ENGINE_RPM_PIN,INPUT_PULLUP);pinMode(PUMP_RPM_PIN,INPUT_PULLUP);pinMode(FLOW_ENABLE,OUTPUT);pinMode(PRESSURE_ENABLE,OUTPUT);setDefaults();loadMachine();led.begin();ledcSetup(FLOW_CH,250,PWM_BITS);ledcSetup(PRESSURE_CH,250,PWM_BITS);ledcSetup(THROTTLE_CH,150,PWM_BITS);ledcAttachPin(FLOW_PIN,FLOW_CH);ledcAttachPin(PRESSURE_PIN,PRESSURE_CH);ledcAttachPin(THROTTLE_PIN,THROTTLE_CH);failSafe();attachInterrupt(digitalPinToInterrupt(ENGINE_RPM_PIN),engineIsr,RISING);attachInterrupt(digitalPinToInterrupt(PUMP_RPM_PIN),pumpIsr,RISING);scale.begin(HX_DOUT,HX_CLK);scaleConnected=scale.wait_ready_timeout(1000);if(scaleConnected){scale.set_scale(machine.loadScale);scale.tare(10);}setupBle();memset(&command,0,sizeof(command));command.magic=DYNO_PACKET_MAGIC;command.version=DYNO_PACKET_VERSION;state=STATE_DISARMED;lastControlUs=micros();}
void loop(){processCommand();processConfig();readSensors();physicalReset();evaluateSafety();uint32_t nowUs=micros();if((uint32_t)(nowUs-lastControlUs)>=CONTROL_US){float dt=(nowUs-lastControlUs)/1000000.0f;lastControlUs=nowUs;runControl(dt);writeOutputs();}uint32_t now=millis();if(now-lastTelemetryMs>=TELEMETRY_MS){lastTelemetryMs=now;sendTelemetry();}delay(1);}
